services:
  rexx:
    build: .
    hostname: rexx
    env_file:
      - ./.env
    environment:
      HTTP_PORT: 8080
      MONGODB_URL: mongodb://mongodb:27017?directConnection=true
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:latest
    hostname: mongodb
    command: mongod --replSet rs0 --bind_ip_all --port 27017
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongodb-test:
    image: mongo:latest
    hostname: mongodb-test
    command: mongod --replSet rs0 --bind_ip_all --port 28017
    ports:
      - "28017:28017"
    volumes:
      - mongodb_test_data:/data/db
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:28017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongodb-setup:
    image: mongo:latest
    depends_on:
      mongodb:
        condition: service_healthy
    command: >
      mongosh --host mongodb:27017 --eval "
        rs.initiate({
          _id: 'rs0',
          members: [
            {_id: 0, host: 'mongodb:27017'}
          ]
        })
      "mongosh --host mongodb-test:28017 --eval "
        rs.initiate({
          _id: 'rs0',
          members: [
            {_id: 0, host: 'mongodb-test:28017'}
          ]
        })
      "

volumes:
  mongodb_data:
  mongodb_test_data:
